[package]
name = "vis"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
js-sys = "0.3.69"
svg = "0.16.0"
proconio = { version = "=0.4.5", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
